server:
 # port: 9191
 # port: 9292
   port: 9393
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_jpa_db
    username: root
    password: 09737895*#Aa
    
  application:
    name: MOVIES-MS
    
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      
      

