server:
  port: 9090
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_jpa_db
    username: root
    password: 09737895*#Aa
    
  application:
    name: DIRECTOR-MS
    
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      
    
#Actuator configuration
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
        

#Resilience4j configuration

resilience4j:
  circuitbreaker:
    instances:
      A-SERVICE:
       registerHealthIndicator: true
       eventConsumerBufferSize: 10
       failureRateThreshold: 50
       minimumNumberOfCalls: 5
       automaticTransitionFromOpenToHalfOpenEnabled: true
       waitDurationInOpenState: 5s
       permittedNumberOfCallsInHalfOpenState: 3
       slidingWindowSize: 10
       slidingWindowType: COUNT_BASED
       
       
       
MOVIES-MS:
ribbon:
  eureka:
    enabled: false
  listOfServers: localhost:9191,localhost:9292,localhost:9393
  ServerListRefreshInterval: 15000



